---
title: "CHURNSET"
author: "mrvn"
date: "2023-06-12"
output: html_document
---

```{r}
library(ggplot2)
library(corrplot)
library(readr)
library(dplyr)
library(caret)
library(ranger)
library(MLmetrics)
library(rpart)
library(rpart.plot)
```

```{r}
df = read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
head(df)
```

```{r}
summary(df)
```

```{r}
str(df)
```

```{r}
colSums(is.na(df))
```

```{r}
sum(duplicated(df))
```

```{r}
# Count the responses
churn_counts <- table(df$Churn)

# Create the bar plot
ggplot(data = data.frame(churn = names(churn_counts),
                         count = as.numeric(churn_counts)),
       aes(x = churn, y = count, fill = churn)) +
  geom_bar(stat = "identity") +
  xlab("Churn") +
  ylab("Count") +
  ggtitle("Count of Yes/No Churn")
```

```{r}

ggplot(data = df, aes(x = Churn, fill = as.factor(SeniorCitizen))) +
  geom_bar(position = "dodge") +
  xlab("Churn") +
  ylab("Senior Citizen") +
  scale_fill_manual(values = c("0" = "blue", "1" = "red")) +
  ggtitle("Count of Churn with Senior Citizen")
```

```{r}
# Reshape the data for plotting
plot_data <- data.frame(
  variable = rep(c("StreamingTV", "StreamingMovies"), each = nrow(df)),
  value = c(df$StreamingTV, df$StreamingMovies),
  churn = rep(df$Churn, times = 2)
)

# Create the stacked bar plot
ggplot(data = plot_data, aes(x = variable, fill = churn)) +
  geom_bar() +
  xlab("Streaming") +
  ylab("Count") +
  scale_fill_manual(values = c("No" = "steelblue", "Yes" = "red")) +
  ggtitle("Count of Streaming with Churn")
```

```{r}
# Calculate the counts for each category
count_data <- data.frame(
  streaming_variable = rep(c("StreamingTV", "StreamingMovies"), each = nrow(df)),
  streaming_value = c(df$StreamingTV, df$StreamingMovies)
)

# Create the grouped bar plot
ggplot(data = count_data, aes(x = streaming_variable, fill = streaming_value)) +
  geom_bar() +
  xlab("Streaming") +
  ylab("Count") +
  scale_fill_manual(values = c("No" = "steelblue", "Yes" = "red", "No internet service" = "green")) +
  ggtitle("Count of Streaming")
```

```{r}
median_value <- median(df$TotalCharges, na.rm = TRUE)
df$TotalCharges[is.na(df$TotalCharges)] <- median_value
colSums(is.na(df))
```

```{r}
# Identify string variables
string_vars <- names(df)[sapply(df, is.character)]

# Encode string variables starting from zero
for (var in string_vars) {
  levels <- unique(df[[var]])
  df[[var]] <- as.integer(factor(df[[var]], levels = levels)) - 1
}

# Print the encoded dataframe
print(df)
```

```{r}
# Set the seed for reproducibility
set.seed(123)

# Create the train-test split
train_indices <- createDataPartition(df$Churn, p = 0.7, list = FALSE)
train <- df[train_indices, ]
test <- df[-train_indices, ]
```

```{r}
# Train the random forest model
RFmodel <- ranger(Churn ~ ., data = train, num.trees = 100)
RFpredictions <- predict(RFmodel, data = test)$predictions


# Decision tree model
DTmodel <- rpart(Churn ~ ., data = train)
DTpredictions <- predict(DTmodel, newdata = test)


# Logistic Regression
LRmodel <- glm(Churn ~ ., data = train, family = "binomial")
LRpredictions <- predict(LRmodel, newdata = test)

# Calculate the AUC score
RFauc_score <- AUC(RFpredictions, test$Churn)
print(paste("RF AUC:", RFauc_score))
DTauc_score <- AUC(DTpredictions, test$Churn)
print(paste("DT AUC:", DTauc_score))
LRauc_score <- AUC(LRpredictions, test$Churn)
print(paste("LR AUC:", LRauc_score))

RFprecision_score <- Precision(test$Churn, RFpredictions)
print(paste("RF precision:", RFprecision_score))
DTprecision_score <- Precision(test$Churn, DTpredictions)
print(paste("DT precision:", DTprecision_score))
LRprecision_score <- Precision(test$Churn, LRpredictions)
print(paste("LR precision:", LRprecision_score))

RFf1_score <- F1_Score(test$Churn, RFpredictions)
RFrecall <- Recall(test$Churn, LRpredictions)
RFaccuracy <- Accuracy(test$Churn, LRpredictions)
print(paste("RF F1 Score:", RFf1_score))
print(paste("RF Recall:", RFrecall))
print(paste("RF Accuracy:", RFaccuracy))

DTf1_score <- F1_Score(test$Churn, DTpredictions)
DTrecall <- Recall(test$Churn, DTpredictions)
DTaccuracy <- Accuracy(test$Churn, DTpredictions)
print(paste("DT F1 Score:", DTf1_score))
print(paste("DT Recall:", DTrecall))
print(paste("DT Accuracy:", DTaccuracy))

LRf1_score <- F1_Score(test$Churn, LRpredictions)
LRrecall <- Recall(test$Churn, LRpredictions)
LRaccuracy <- Accuracy(test$Churn, LRpredictions)
print(paste("LR F1 Score:", LRf1_score))
print(paste("LR Recall:", LRrecall))
print(paste("LR Accuracy:", LRaccuracy))

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```